### ISSUE TITLE
UpdatePluginConf seems to have no effect when called from Enable()/Disable()

### ISSUE THREAD

**Issue by buckket** [gotify/plugin-api#4]
I’m trying to reset all stored data when my plugin gets enabled/disabled. To archive this I’m calling `c.storageHandler.Save()` from within the plugin’s `Enable()` or `Disable()` methods. This seems to have no effect however. In other cases the `storageHandler` works as expected.

Looking at https://gotify.net/docs/plugin-write#storager it seems that it should be possible.

I’m developing against gotify-server v2.0.5

**Comment by eternal-flame-AD** [comment]
Can you provide a minimal reproduction example and describe the difference between what you expected and what was done?

**Comment by buckket** [comment]
I created this [example plugin](https://gist.github.com/buckket/7d8766fd4939f78830b8281dd4ec49ff).

**Expected behavior:**
GetDisplay() should return either "Set via Enable()" or "Set via Disable()" after enabling/disabling the plugin.

> TestStorage: Set via Enable()

**Observed behavior:**
c.storageHandler.Load() always returns a zero byte slice.
> Could not parse storage data: unexpected end of JSON input ([])

**Comment by eternal-flame-AD** [comment]
Thanks for the work:) I have located the problem and will submit a fix
