### ISSUE TITLE
Unraid Plugin Not working

### ISSUE THREAD

**Issue by pfckiko** [gotify/plugin-api#5]
Does anyone know or having any experience in getting the pluggings installed on the  Unraid Gotify container? I can't figure out what I am doing wrong and have not had any type of success getting the plugins installed. the only one I really need is the webhook plugin.
 I know someone will be reading this and say 
![image](https://media1.giphy.com/media/j5TuBLY1lTXBC/source.gif)
but while you say that please help me. the tutorials I read are not working. so far I was able to install **GO** inside the docker image but when I try to install the plugin by using **Go Build** command it says 

```
# command-line-arguments
./webhook.go:7:2: undefined: Plugin
```
then I try to run it as root and instead of building it I run it by using the command  
**su root ./webhook.go**  and I get this error 
```
./webhook.go: line 1: package: not found
./webhook.go: line 3: import: not found
./webhook.go: line 5: //: Permission denied
Webhooker: not found
interface: not found
{ is a shell keyword
./webhook.go: line 7: Plugin: not found
./webhook.go: line 8: //: Permission denied
./webhook.go: line 9: syntax error: unexpected word (expecting ")")
``` 
![image](https://media.giphy.com/media/9u1mPQs4JPVY3sokXp/giphy.gif)
If you charge for your time and the price is not high I might be able to pay you just let me know.

**Comment by jmattheis** [comment]
One issue is enough :D.
