### ISSUE TITLE
User/Plugin authentication

### ISSUE THREAD

**Issue by tystuyfzand** [gotify/plugin-api#9]
I'd love to have an API that allows plugins to check authentication tokens/passwords against Gotify itself.

A good example is using my gotify-smtp plugin, it'd be great to validate the app token as a password and allow it to be a bit more secure rather than forcing users to firewall it properly.

**Comment by jmattheis** [comment]
You could use the https://gotify.net/docs/plugin-write#storager interface and do something like:
* Create random string
* Store it inside the storager
* compare the random string against the password when sending a mail
* Display it to the user and say that the random string must be used as the password via https://gotify.net/docs/plugin-write#displayer

**Comment by tystuyfzand** [comment]
I guess that does make more sense... was more hoping users on gotify could specify their own and route to it, but it definitely makes sense to just have a key/password defined in the settings. Thanks!
